server:
  port: 9082
  servlet:
    context-path: /webclient-products

swagger:
  enabled: true


spring:
  data:
    mongodb:
      uri: mongodb://admin:masterkey@localhost:27017/webclientsample?authSource=admin
      auto-index-creation: true