server:
  port: 9081
  servlet:
    context-path: /webclient-images

swagger:
  enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://admin:masterkey@localhost:27017/webclientsample?authSource=admin
      auto-index-creation: true